name: fitpro
description: A minimalist fitness recovery app for university students.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.20.0
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.10.0
  firebase_storage: ^11.5.0
  google_sign_in: ^6.2.1
  provider: ^6.1.1
  flutter_local_notifications: ^15.1.1
  firebase_messaging: ^14.7.0
  flutter_dotenv: ^5.1.0
  image_picker: ^1.1.0
  sensors_plus: ^3.0.2
  url_launcher: ^6.2.5
  fluttertoast: ^8.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

